# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Profile Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  heading:
  subheading: Subheading.
  background_image:
  alt_text:
  styles:
    vibe: down-to-business
    background_c:
    gradient_1:
    gradient_2:
    gradient_3:
    heading_c:
    enable_blend: false
    enable_pattern: false
    tint_opacity: "0.5"
    container_margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alt_text:
    hidden: '!background_image'
    options:
      required: true
  background_image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
      prevent_resize_existing_files: false