# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Contact Us"
  description: Contact details.
  icon: contact_phone
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  phones:
    phones_items:
    ctas:
  emails:
    emails_items:
    ctas:
  faxes:
    faxes_items:
    ctas:
  offices:
    offices_items:
    ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: contact-us
      edit_mode_only: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  # Settings
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  bg_subtle:
    type: checkbox
  buffer:
    type: select
    options:
      allow_empty: true
      values: _select_data.buffers
      value_key: class
    cascade: true
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
    cascade: true
  emails_items:
    label: Items
    options:
      structures: _structures.emails_items
  faxes_items:
    label: Items
    options:
      structures: _structures.faxes_items
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  margin:
    type: select
    options:
      allow_empty: true
      values: _select_data.container_margins
      value_key: class
    cascade: true
  lines:
    type: array
  lines[*]:
    type: text
  offices_items:
    label: Items
    options:
      structures: _structures.offices_items
  padding:
    type: auto
    hidden: true
  phones_items:
    label: Items
    options:
      structures: _structures.phones_items
  remove_container_background:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  tint_opacity:
    type: select
    options:
      allow_empty: true
      values: _select_data.tint_opacities
      value_key: value
    comment: >-
      Use to improve text legibility when applying a background image. Disabled
      when blend is enabled.
    cascade: true
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  ctas:
    type: array
    options:
      structures: _structures.links
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  buffers:
    - name: Buffer Top
      class: pt-6
    - name: Buffer Bottom
      class: pb-6
    - name: Buffer Both
      class: py-6
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8
  container_margins:
    - name: Pull Up
      class: mt-n8 mt-xxl-n9
  tint_opacities:
    - name: None
      value: '0.0'
    - name: Light
      value: '0.3'
    - name: Medium
      value: '0.5'
    - name: Dark
      value: '0.7'
_structures:
  emails_items:
    values:
      - value:
          heading:
          email:
  faxes_items:
    values:
      - value:
          heading:
          fax:
  links:
    values:
      - value:
          text:
          icon:
          url:
  offices_items:
    values:
      - value:
          heading:
          lines:
  phones_items:
    values:
      - value:
          heading:
          phone: