# Metadata about this component, to be used in the CMS
spec:
  structures:
    - photo_essay_blocks
    - place_blocks
  label: "Gallery"
  description: A gallery of images
  icon: collections
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  name:
  heading:
  subheading:
  images:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  images:
    type: array
    options:
      structures: _structures.images
_structures:
  images:
    values:
      - label: "Image"
        value:
          image_source:
          image_alt:
          image_caption:
        preview:
          text:
            - key: image_alt
            - "Image"
          subtext: 
            - key: image_source
          image: 
            - key: image_source
          icon: image
          metadata:
            - icon: closed_caption
              text:
                - key: image_caption
        _inputs:
          image_source:
            type: image
          image_caption:
            type: textarea