# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "CTA Buttons"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  buttons:
    - text:
      icon:
      url:
      button_c:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
_select_data:
  brand_colors:
    - name: Default
      class: wvu-b-btn
    - name: Gold
      class: btn-wvu-gold
    - name: Blue
      class: btn-wvu-blue
    - name: Safety Blue
      class: btn-wvu-accent--blue
    - name: Coal
      class: btn-wvu-accent--blue-dark
    - name: Star City Blue
      class: btn-wvu-accent--blue-light
    - name: Canary
      class: btn-wvu-accent--yellow
    - name: Old Gold
      class: btn-wvu-accent--old-gold
    - name: Sunset
      class: btn-wvu-accent--sunset
    - name: Not Quite White
      class: btn-wvu-neutral--off-white
    - name: Cooper's Gray
      class: btn-wvu-neutral--warm-gray-light
    - name: Seneca Gray
      class: btn-wvu-neutral--warm-gray-medium
    - name: Rattler Gray
      class: btn-wvu-neutral--warm-gray-dark
    - name: Wild Flour
      class: btn-wvu-neutral--cream
    - name: Buckskin
      class: btn-wvu-neutral--tan