# Metadata about this component, to be used in the CMS
spec:
  structures:
    - article_topper
  label: "Topper - Article"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  show_byline: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    hidden: true
  subheading:
    hidden: true