# Metadata about this component, to be used in the CMS
spec:
  structures:
    - masthead_lockups
  label: "Standard Logo Lockup"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  super_heading:
  lockup_lines:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  lockup_lines:
    type: array
  lockup_lines[*]:
    type: text
  super_heading:
    hidden: true