# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - column_sm_blocks
    - content_blocks
    - detail_blocks
  label: "Separator"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  separator_c:
  settings:
    styles:
      background_c: transparent
    layout:
      margin: my-xl-n6 my-xxl-n7
      padding: py-xl-0 py-xxl-0
    config:
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  separator_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Color