# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Tabs"
  description: Tabbed UI.
  icon: tabs
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  tabs:
    - label: Tab
      text: Tab text.
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam