# Metadata about this component, to be used in the CMS
spec:
  structures:
    - student_profile_topper
  label: "Topper - Student Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  heading:
  subheading:
  styles:
    vibe: down-to-business
    background_c:
    gradient_1:
    gradient_2:
    gradient_3:
    heading_c:
    enable_blend: false
    enable_pattern: false
    tint_opacity: "0.5"
    container_margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  enable_blend:
    hidden: true