# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Faculty Members"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Faculty
  tags:
  postscript:
    copy:
    ctas:
  config:
    show_content: false
  is_dynamic: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    options:
      allowed_sources:
        - ccdam
  ctas:
    type: array
    options:
      structures: _structures.links
    cascade: true
  is_dynamic:
    hidden: true
_structures:
  links:
    style: select
    values:
      - value:
          text:
          icon:
          url: