# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "YouTube Shorts"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Shorts
  subheading:
  shorts:
    - title:
      video_id:
      ratio: 9x16
  postscript:
    copy:
    ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name:
      instance:
      edit_mode_only: false
      include_heading_postscript: true
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  ratio:
    hidden: true