# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
  label: "Article Collection"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Articles
  tags:
  limit: 5
  config:
    show_content: false
    hide_thumbnails: false
  id_dynamic: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  limit:
    type: number
  tags:
    type: multiselect
    options:
      allow_create: true
      allow_empty: true
      values:
        - featured