# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  alt_text:
  heading: Heading
  subheading: Subheading.
  body_text:
  settings:
    styles:
      background_c:
      gradient:
      heading_c:
      enable_blend: false
      enable_pattern: false
      tint_opacity: "0.5"
    layout:
      margin:
      buffer:
      text_placement:
    config:
      show_label: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    hidden: true
  highlight:
    hidden: true
  body_text:
    type: markdown
  container_margin:
    type: select
    options:
      values: _select_data.topper_margins
      value_key: class
  enable_pattern:
    hidden: true