# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Sitewide Section"
  description: Pull in a component from site settings.
  icon: globe
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  sitewide_section:
  show_content: false
  # show: 2024-09-01
  # hide: 2099-09-01
  is_sitewide: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  hide:
    type: datetime
    options:
      timezone: America/New_York
  is_sitewide:
    hidden: true
  show:
    type: datetime
  sitewide_section:
    type: select
    options:
      allow_empty: true
      values: data.sitewide_components.sitewide_components