# Metadata about this component, to be used in the CMS
spec:
  structures:
    - staff_profile_topper
  label: "Topper - Staff"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  settings:
    styles:
      audience:
      tone: default
      color_palette: option-1
      tint_opacity: "0.7"
    layout:
      background_position:
      text_placement: mx-auto
    config:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: