# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - default_content_blocks
  label: "Quicklinks"
  description: A collection of relevant links.
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Quicklinks
  subheading:
  links:
    - text: Text
      url: /url
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: quicklinks
      edit_mode_only: false
      include_heading_postscript: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: