# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero Test"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  heading: Heading
  subheading: Subheading.
  markdown:
  cta_buttons: bookshop:design-system/simple/cta-buttons!
  postscript:
    markdown:
    cta_list_inline:
  settings:
    styles:
      audience: general
      tone: loud
      color_palette: option-2
      enable_blend: false
      enable_pattern: false
      tint_opacity: "0.7"
      heading_size: display-2
    layout:
      buffer:
      text_placement: mx-auto text-center
      background_position:
    config:
      show_label: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_size:
    hidden: true
  enable_pattern:
    hidden: true
  markdown:
    options:
      allowed_sources:
        - ccdam