# Metadata about this component, to be used in the CMS
spec:
  structures:
    - topper
  label: "Topper - Hero Test"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  alt_text:
  heading:
    - text: Heading
      highlight:
  subheading: Subheading.
  body_text:
  styles:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    hidden: true
  highlight:
    hidden: true
  body_text:
    type: markdown
  container_margin:
    type: select
    options:
      values: _select_data.topper_margins
      value_key: class
  styles:
    type: object
    options:
      values:
        value:
          - vibe
          - background_c
          - color_overlay
          - heading_c
          - enable_blend
          - enable_pattern
          - tint_opacity
          - container_margin