# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Big Search"
  description:
  icon: search
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: Label
  heading: Big Search Heading
  subheading: Subheading.
  postscript:
    copy:
    postscript_links:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name:
      instance:
      edit_mode_only: false
      include_heading_postscript: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
