# Metadata about this component, to be used in the CMS
spec:
  structures:
    - article_blocks
    - column_sm_blocks
    - detail_blocks
  label: "Rich Text"
  description: Add formatted text.
  icon: edit_note
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: Text.
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  text:
    type: markdown
    options:
      blockquote: true
      bold: true
      bulletedlist: true
      embed: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      image: true
      indent: true
      join_above: true
      join_below: true
      link: true
      numberedlist: true
      outdent: true
      strike: true
      subscript: true
      superscript: true
      table: true
      underline: true
      code: true
      style: /assets/scss/custom/_content.scss
      allowed_sources:
        - ccdam