# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Article Collection"
  description:
  icon: library_books
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Article Collection Heading
  tags:
  postscript:
    copy:
    ctas:
  config:
    limit:
    show_content: false
    hide_thumbnails: false
    is_dynamic: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  limit:
    type: number
  copy:
    options:
      allowed_sources:
        - ccdam