# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "FAQs"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Frequently Asked Questions
  items:
    - question:
      answer:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  answer:
    type: markdown
    options:
      allowed_sources:
        - ccdam