# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Program Collection"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  items:
    - title: Item 1 Title
      text: Item 1 text.
      site_page:
      url:
    - title: Item 2 Title
      text: Item 2 text.
      site_page:
      url:
    - title: Item 3 Title
      text: Item 3 text.
      site_page:
      url:
  lead: Lead text.
  settings:
    styles:
      item_headings:
    layout:
      margin_y:
    config:
      name: program-collection
      edit_mode_only: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true
      
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  settings:
    type: object
    options:
      subtype: tabbed
  use_common_wrapper:
    type: auto
    hidden: true