# Metadata about this component, to be used in the CMS
spec:
  structures:
    - alumni_profile_topper
  label: "Topper - Alumni Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  alt_text:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      tint_opacity: "0.7"
    layout:
      background_position:
    config:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: