# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Vertical Subnav"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  v_menu:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  v_menu:
    type: select
    label: Menu
    options:
      values: data.menus[?(@._schema == "vertical_subnav")]
      value_key: uuid
      preview:
        text:
          - key: subnav_title
    context:
      content: This will appear just below the main nav on this page. Note, it will not show in the Live Editor until the next time your page builds.