# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Featurettes - Vertical"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      image:
      alt_text:
      label:
      badge:
      text: Item 1 text.
      ctas:
  postscript:
    copy:
    ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      _padding: py-6 py-xxl-7
    config:
      edit_mode_only: false
      include_heading_postscript: true
      show: 2024-09-01
      hide: 2099-09-01

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  badge:
    hidden: true
  label:
    hidden: true
  text:
    type: textarea