# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Columns 2-1-1"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  column_a:
  column_aaa:
  column_bbb:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      show_label: true
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01
  _is_nested: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: