# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Columns 2-1-1"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  column_a:
  column_b:
  column_c:
  settings:
    styles:
      background_c:
      gradient:
      heading_c:
      enable_blend: false
      enable_pattern: false
      tint_opacity: "0.5"
    layout:
      margin:
      buffer:
      text_placement:
      padding: py-5 py-xxl-6
    config:
      show_label: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: