# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - detail_blocks
  label: "Featurettes - Vertical"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      image:
      alt_text:
      label:
      badge:
      text: Item 1 text.
      ctas:
  settings:
    styles:
      audience:
    layout:
    config:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  badge:
    hidden: true
  config:
    hidden: true
  layout:
    hidden: true
  label:
    hidden: true
  text:
    type: textarea