# Metadata about this component, to be used in the CMS
spec:
  structures:
    - color_overlay
  label: "Tint Overlay"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  opacity: "0.5"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: