# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Search"
  description:
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  search_id: search-component
  label:
  background_image:
  alt_text:
  heading: Heading
  subheading: Subheading.
  placeholder: Type in your search term.
  postscript:
    markdown:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      buffer:
      padding: py-6 py-xxl-7
    config:
      name: search
      edit_mode_only: false
      include_heading_postscript: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alt_text:
    hidden: '!background_image'
    options:
      required: true
  heading:
    options:
      required: true
  markdown:
    options:
      allowed_sources:
        - ccdam
  name:
    options:
      required: true
  search_id:
    options:
      required: true