# Metadata about this component, to be used in the CMS
spec:
  structures:
    - faculty_contact_info
    - staff_contact_info
  label: "Office"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: Office
  location: 438 Woodburn Hall
  map_link:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  location:
    type: text