# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Article Hero Test"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  show_byline: false
  settings:
    styles:
      tint_opacity: "0.7"
    layout:
      text_placement: mx-auto text-start
      # background_position:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  settings:
    type: object
    options:
      subtype: tabbed