# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Cards"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      image:
      alt_text:
      label:
      badge:
      text: Item 1 text.
      ctas:
      background_c:
      accent_c:
  postscript:
    copy:
    ctas:
  settings:
    layout:
      buffer:
      margin:
      pading: py-6 py-xxl-7
    styles:
      audience:
      vibe:
      color_palette:
      tint_shade:
    config:
      edit_mode_only: false
      include_heading_postscript: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  accent_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Accent Color
  padding:
    hidden: true