# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Cards"
  description: Grid of cards (photo, headline, CTA).
  icon: library_books
  tags: [Lists]

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  aria_label:
  items:
    - title: Item 1 Title
      image:
      alt_text:
      # label:
      # badge:
      text: Item 1 text.
      ctas:
  postscript:
    copy:
    # ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      # enable_blend: false
      # tint_opacity: '0.7'
      # remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: cards
      edit_mode_only: false
      include_heading_postscript: true
      # # show: 2024-09-01
      # # hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  aria_label:
    label: ARIA Label
    hidden: '!heading'
    options:
      required: true
    context:
      content: If your component doesn’t have a heading, it needs an <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label">ARIA label</a> to be accessible. Enter a concise label to provide a clear and useful name for this component e.g. “Featured News Stories.’
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  bg_subtle:
    type: checkbox
  buffer:
    type: select
    options:
      allow_empty: true
      values: _select_data.buffers
      value_key: class
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
  hide:
    type: datetime
    options:
      timezone: America/New_York
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  margin:
    type: select
    options:
      allow_empty: true
      values: _select_data.container_margins
      value_key: class
  padding:
    type: auto
    hidden: true
  remove_container_background:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  show:
    type: datetime
  subheading:
    hidden: '!heading'
  tint_opacity:
    type: select
    options:
      allow_empty: true
      values: _select_data.tint_opacities
      value_key: value
    comment: >-
      Use to improve text legibility when applying a background image. Disabled
      when blend is enabled.
    cascade: true
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  alt_text:
    hidden: '!image'
    options:
      required: true
  accent_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Accent Color
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  ctas:
    type: array
    options:
      structures: _structures.links
    cascade: true
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
  text:
    type: textarea
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  buffers:
    - name: Buffer Top
      class: pt-6
    - name: Buffer Bottom
      class: pb-6
    - name: Buffer Both
      class: py-6
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8
  container_margins:
    - name: Pull Up
      class: mt-n8 mt-xxl-n9
  tint_opacities:
    - name: None
      value: '0.0'
    - name: Light
      value: '0.3'
    - name: Medium
      value: '0.5'
    - name: Dark
      value: '0.7'
_structures:
  links:
    values:
      - value:
          text:
          icon:
          url: