# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_sidebar_blocks
  label: "Info Card"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  copy:
  card_c:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  card_c:
    hidden: true
  is_dynamic:
    hidden: true