# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - place_blocks
  label: "Alternating Grid Test 2"
  description: Alternating content blocks w/a photo, text call-to-action.
  icon: sync_alt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Alternating Grid Heading
  subheading: Subheading goes here.
  background_image:
  items:
    - heading: Item Heading
      image:
      alt_text:
      copy:
      ctas:
  postscript:
    copy:
    ctas:
  settings:
    styles:
      background_c:
      gradient:
      heading_c:
      enable_blend: false
      enable_pattern: false
      tint_opacity: "0.5"
    layout:
      butter:
      margin:
    config:
      edit_mode_only: false
      include_heading_postscript: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    type: markdown
  include_heading_postscript:
    hidden: true