# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Buttons"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  buttons:
    - text:
      url:
      button_c:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_c:
    options:
      values: _select_data.brand_colors
      value_key: class