# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Profile - Generic"
  description:
  icon: person
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  name: Firstname Lastname
  image:
  label:
    - Label
  info:
    - Morgantown, WV
  ctas:
  settings:
    styles:
      audience:
      background_c:
    layout:
      is_cutout: false
      margin_no_bg:
      buffer:
      padding: py-0
    config:
      edit_mode_only: false
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  audience:
    type: select
    options:
      values:
        - alumni
        - prospective_students
  is_cutout:
    type: switch
    label: Use Cutout
    subtext: Choose this if you’ve cut your profile image from the background.
  margin_no_bg:
    label: Margin