# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Profile - Generic"
  description:
  icon: person
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  component_name: profile-generic
  heading: Heading
  name: Firstname Lastname
  image:
  super_heading:
    - Label
  info:
    - Morgantown, WV
  copy:
  ctas:
  settings:
    styles:
      audience:
      tone:
      card_c:
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      butter:
      margin_no_bg:
      padding: py-6 py-xxl-7
    config:
      edit_mode_only: false
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  accent_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
  card_c:
    type: select
    label: Card Color
    options:
      values:
        - name: Option 1
          class: option-1
        - name: Option 2
          class: option-2
        - name: Option 3
          class: option-3
      value_key: class
  copy:
    type: textarea
  is_cutout:
    type: switch
    label: Use Cutout
    subtext: Choose this if you’ve cut your profile image from the background.
  level:
    type: number
  margin_no_bg:
    label: Margin
  name:
    hidden: true