# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Student Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  student:
  config:
    name:
    instance:
    edit_mode_only: false
    show_content: false
  styles:
    color_palette: option-1
    vibe:
    volume:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: