# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "CTA Banner"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  buttons:
    - text:
      url:
      icon:
      button_c:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name:
      instance:
      edit_mode_only: false
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  button_c:
    hidden: true
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Button Color
  buttons_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Button Color