# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_sidebar_blocks
  label: "Link List Panels"
  description: Panels for linking to downloads or pages.
  icon: splitscreen
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  list_description:
  items:
    - text:
      description:
      url: 
      icon:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    label: Label
  is_dynamic:
    hidden: true
  list_description:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  icon:
    type: select
    options:
      values:
        - PDF
        - Download
        - Link
  url:
    options:
      allowed_sources:
        - ccdam