# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_sidebar_blocks
    - profile_sidebar_blocks
  label: "CTA Stack"
  description: Stack of featured links.
  icon: table_rows
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Links
  ctas:
    - text:
      url:
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true