# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Benefits Checklist"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      text: Item 1 text.
  benefits_icon: circle-check

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  badge:
    hidden: true
  config:
    hidden: true
  layout:
    hidden: true
  label:
    hidden: true
  text:
    type: markdown
  title:
    options:
      required: false
  benefits_icon:
    label: Icon
    type: select
    options:
      values:
        - name: Checkmark
          class: circle-check
        - name: Arrow
          class: arrow-circle-right
      value_key: class