# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Calendar Events"
  description: List calendar events.
  icon: calendar_month
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Upcoming Events
  subheading:
  event_feed:
  postscript:
    text:
    ctas:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      is_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      butter:
      margin:
      padding: py-6 py-xxl-7
    config:
      edit_mode_only: false
      include_heading_postscript: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  event_feed: textarea