# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Calendar Events"
  description: List calendar events.
  icon: calendar_month
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Upcoming Events
  subheading:
  event_feed:
  postscript:
    text:
    ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: calendar-events
      edit_mode_only: false
      include_heading_postscript: true
      show: 2024-09-01
      hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  event_feed: textarea
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam