# Metadata about this component, to be used in the CMS
spec:
  structures:
    - postscript_ctas
  label: "Generic Button Group"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  buttons:
    - text:
      url:
      icon:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
