# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - detail_blocks
  label: "Poster"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  image:
  alt_text:
  body:
  ctas:
  postscript_links:
  settings:
    styles:
      audience:
      tone:
      card_c:
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  body:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  config:
    hidden: true
  text_align:
    hidden: true