# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
  label: "Cards - Vertical"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      image:
      alt_text:
      label:
      badge:
      markdown: Item 1 text.
      ctas:
  postscript:
    copy:
    ctas:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  accent_c:
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
    label: Accent Color
  copy:
    options:
      allowed_sources:
        - ccdam