# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Jump Links"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title:
  items:
    - text:
      description:
      anchor:
  settings:
    styles:
      audience:
      tone:
      color_palette:
    config:
      name: jump-links
      edit_mode_only: false
      include_heading_postscript: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  title:
    hidden: true
    options:
      required: false
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8