# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
  label: "Column Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  component_name: profile-generic
  label: Spotlight
  heading: Heading
  name: Firstname Lastname
  image:
  is_cutout: false
  super_heading:
    - Label
  info:
    - Morgantown, WV
  copy:
  ctas:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
    cascade: true