# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  background_image:
  alt_text:
  lead:
  copy:
  ctas:
  postscript_links:
  settings:
    styles:
      background_c:
    layout:
      margin:
      buffer:
    config:
      edit_mode_only: false
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
