# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  label:
  subheading:
  background_image:
  alt_text:
  body_text:
  ctas:
  postscript_links:
  settings:
    styles:
      audience: general
      tone: loud
      color_palette: option-2
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      buffer:
      padding: py-6 py-xxl-7
      text_placement: mx-auto text-center
      background_position:
    config:
      name: hero
      edit_mode_only: false
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  # Settings
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  bg_subtle:
    type: checkbox
  buffer:
    type: select
    options:
      allow_empty: true
      values: _select_data.buffers
      value_key: class
    cascade: true
  color_palette:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
    cascade: true
  padding:
    type: auto
    hidden: true
  tint_opacity:
    type: select
    options:
      allow_empty: true
      values: _select_data.tint_opacities
      value_key: value
    comment: >-
      Use to improve text legibility when using a background image. Disabled
      when blend is enabled.
    cascade: true
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  alt_text:
    options:
      required: '!background_image'
  background_image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
      prevent_resize_existing_files: false
  body_text:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  ctas:
    type: array
    options:
      structures: _structures.links
_select_data:
  buffers:
    - name: Buffer Top
      class: pt-6
    - name: Buffer Bottom
      class: pb-6
    - name: Buffer Both
      class: py-6
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8
  container_margins:
    - name: Pull Up
      class: mt-n8 mt-xxl-n9
    - name: Pull Down
      class: mb-n8 mb-xxl-n9
    - name: Pull Both
      class: my-n8 my-xxl-n9
  tint_opacities:
    - name: None
      value: '0.0'
    - name: Light
      value: '0.3'
    - name: Medium
      value: '0.5'
    - name: Dark
      value: '0.7'
_structures:
  links:
    values:
      - value:
          text:
          icon:
          url: