# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  background_image:
  alt_text:
  lead:
  copy:
  ctas:
  postscript_links:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      tint_opacity: "0.5"
    layout:
      margin:
      buffer:
      padding: py-7 py-xxl-9
      text_placement: mx-auto text-start
    config:
      edit_mode_only: false
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
