# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Accordion"
  description:
  icon: top_panel_open
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  panels:
    - name: Panel Title
      image:
      alt_text:
      heading: Panel Heading
      text: Panel text.
      ctas:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      bg_subtle:
    layout:
      butter:
      margin:
      padding: py-6 py-xxl-7
    config:
      edit_mode_only: false
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown