# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Accordion"
  description:
  icon: top_panel_open
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  panels:
    - name: Panel Title
      image:
      alt_text:
      heading: Panel Heading
      text: Panel text.
      ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
      remove_container_background: false
    config:
      name: accordion
      edit_mode_only: false
      show: 2024-09-01
      hide: 2099-09-01
      include_heading_postscript: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam