# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_sidebar_blocks
  label: "Contacts"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Contacts
  people:
    - label: "Inquiries"
      contact:
  config:
    hide_thumbnails: false
    show_content: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  contact:
    type: select
    options:
      allow_empty: false
      values: data.people_data[?(@.is_contact == true)]
      value_key: uuid