# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Topper - Big Search"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  alt_text:
  heading: Heading
  subheading: Subheading.
  placeholder: Type in your search term.
  markdown:
  postscript:
    markdown:
    ctas:
  settings:
    styles:
      audience: general
      tone: loud
      color_palette: option-2
      enable_blend: false
      enable_pattern: false
      tint_opacity: "0.7"
      heading_size: display-2
    layout:
      buffer:
      text_placement: mx-auto text-center
    config:
      show_label: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alt_text:
    hidden: '!background_image'
    options:
      required: true
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  heading_size:
    type: select
    options:
      allow_empty: true
      values:
        - name: Large
          class: display-2
        - name: Medium
          class: display-3
        - name: Small
          class: display-4
  markdown:
    options:
      allowed_sources:
        - ccdam
  settings:
    type: object
    options:
      subtype: tabbed