# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Poster - Split"
  description: Two-column layout with text block and image.
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  image:
  alt_text:
  body:
  ctas:
  postscript_links:
    - text: 
      url:
      icon:
  settings:
    styles:
      audience: general
      tone: default
      card_c: option-2
      bg_subtle:
      # enable_blend: false
      # tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin_no_bg:
      padding: py-6 py-xxl-7
      max_cols: 20
    config:
      name: poster-split
      edit_mode_only: false
      include_heading_postscript: false
      # show: 2024-09-01
      # hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  # Settings
  alt_text:
    hidden: '!image'
    options:
      required: true
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  bg_subtle:
    type: checkbox
  buffer:
    type: select
    options:
      allow_empty: true
      values: _select_data.buffers
      value_key: class
    cascade: true
  card_c:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
    cascade: true
  hide:
    type: datetime
    options:
      timezone: America/New_York
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  max_cols:
    hidden: true
  padding:
    type: auto
    hidden: true
  postscript_links:
    type: array
    options:
      structures: _structures.links
  settings:
    type: object
    options:
      subtype: tabbed
  show:
    type: datetime
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
  body:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  margin_no_bg:
    type: select
    label: Margin
    options:
      allow_empty: true
      values: _select_data.container_margins_no_bg
      value_key: class
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  buffers:
    - name: Buffer Top
      class: pt-6
    - name: Buffer Bottom
      class: pb-6
    - name: Buffer Both
      class: py-6
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8
  container_margins_no_bg:
    - name: Pull Up
      class: mt-n9
    - name: Pull Down
      class: mb-n9
    - name: Pull Both
      class: my-n9
  # tint_opacities:
  #   - name: None
  #     value: '0.0'
  #   - name: Light
  #     value: '0.3'
  #   - name: Medium
  #     value: '0.5'
  #   - name: Dark
  #     value: '0.7'
_structures:
  links:
    values:
      - value:
          text:
          icon:
          url: