# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Separator"
  description: A dotted horizontal line for visual separation between sections.
  icon: horizontal_rule
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  separator_c:
  sticker:
  settings:
    styles:
      background_c: transparent
    layout:
      margin: my-xl-n6 my-xxl-n7
      padding: py-xl-0 py-xxl-0
    config:
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_c:
    type: select
    options:
      allow_empty: true
      values: _select_data.brand_colors
      value_key: class
    label: Background Color
  include_heading_postscript:
    hidden: true
  layout:
    hidden: true
  margin:
    type: select
    hidden: true
    options:
      allow_empty: true
      values: _select_data.container_margins
      value_key: class
  padding:
    hidden: true
  separator_c:
    label: Line Color
    type: select
    options:
      values: _select_data.brand_colors
      value_key: class
  settings:
    type: object
    hidden: true
    options:
      subtype: tabbed
  sticker:
    type: select
    options:
      values:
        - name: Black Bear
          path: https://static.wvu.edu/global/images/stickers/black-bear.webp
        - name: Cardinal
          path: https://static.wvu.edu/global/images/stickers/cardinal.webp
        - name: Coonskin Cap
          path: https://static.wvu.edu/global/images/stickers/coonskin-cap.webp
        - name: Honey Bee
          path: https://static.wvu.edu/global/images/stickers/honey-bee.webp
        - name: Mountaineer Statue
          path: https://static.wvu.edu/global/images/stickers/mountaineer-statue.webp
        - name: PRT
          path: https://static.wvu.edu/global/images/stickers/prt.webp
        - name: Trout
          path: https://static.wvu.edu/global/images/stickers/trout.webp
        - name: Woodburn
          path: https://static.wvu.edu/global/images/stickers/woodburn.webp
        - name: WVU Pennant
          path: https://static.wvu.edu/global/images/stickers/wvu-pennant.webp
      value_key: path
  use_common_wrapper:
    type: auto
    hidden: true
_select_data:
  brand_colors:
    - name: WVU Gold
      background_classes: bg-wvu-gold text-dark
      class: wvu-gold
      rgba: 234,170,0
    - name: WVU Blue
      background_classes: bg-wvu-blue text-white
      class: wvu-blue
      rgba: 0, 40, 85
    - name: Safety Blue
      background_classes: bg-wvu-safety-blue text-white
      class: wvu-safety-blue
      rgba: 0, 98, 163
    - name: Coal
      background_classes: bg-wvu-coal text-white
      class: wvu-coal
      rgba: 28, 43, 57
    - name: Star City Blue
      background_classes: bg-wvu-star-city-blue text-dark
      class: wvu-star-city-blue
      rgba: 157, 218, 230
    - name: Canary
      background_classes: bg-wvu-canary text-dark
      class: wvu-canary
      rgba: 255, 229, 57
    - name: Old Gold
      background_classes: bg-wvu-old-gold text-white
      class: wvu-old-gold
      rgba: 127, 99, 16
    - name: Sunset
      background_classes: bg-wvu-sunset text-dark
      class: wvu-sunset
      rgba: 245, 134, 114
    - name: Not Quite White
      background_classes: bg-wvu-not-quite-white text-dark
      class: wvu-not-quite-white
      rgba: 247, 247, 247
    - name: Cooper's Gray
      background_classes: bg-wvu-coopers-gray text-dark
      class: wvu-coopers-gray
      rgba: 190,183,179
    - name: Seneca Gray
      background_classes: bg-wvu-seneca-gray text-dark
      class: wvu-seneca-gray
      rgba: 152, 142, 139
    - name: Rattler Gray
      background_classes: bg-wvu-rattler-gray text-white
      class: wvu-rattler-gray
      rgba: 85, 71, 65
    - name: Wild Flour
      background_classes: bg-wvu-wild-flour text-dark
      class: wvu-wild-flour
      rgba: 242, 230, 194
    - name: Buckskin
      background_classes: bg-wvu-buckskin text-dark
      class: wvu-buckskin
      rgba: 179, 161, 105
    - name: Transparent (Dark Text)
      background_classes: bg-transparent text-dark
      class: transparent
      rgba:
    - name: Transparent (Light Text)
      background_classes: bg-transparent text-white
      class: transparent
      rgba:
    - name: Dark
      background_classes: bg-dark text-white
      class: dark
      rgba: 42, 42, 41
  container_margins:
    - name: Pull Up
      class: mt-n8 mt-xxl-n9
    - name: Pull Down
      class: mb-n8 mb-xxl-n9
    - name: Pull Both
      class: my-n8 my-xxl-n9