# Metadata about this component, to be used in the CMS
spec:
  structures:
    - article_topper
  label: "Topper - Article Hero"
  description:
  icon: crown
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background_image:
  alt_text:
  heading:
  body_text:
  show_byline: false
  styles:
    vibe: down-to-business
    background_c:
    gradient_1:
    gradient_2:
    gradient_3:
    heading_c:
    enable_blend: false
    enable_pattern: false
    tint_opacity: "0.5"
    margin:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    hidden: true
  label:
    hidden: true
  vibe:
    hidden: true