# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Contact Us"
  description:
  icon: contact_phone
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading:
  office:
  phone:
  fax:
  email:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name:
      instance:
      edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  email:
    options:
      values: _structures.email
  office:
    options:
      values: _structures.office
  phone:
    options:
      values: _structures.phone
_structures:
  email:
    values:
      value:
        heading: By Email
        icon: envelope
        items:
          - heading:
            email:
  office:
    values:
      value:
        heading: At the Office
        icon: location-dot
        items:
          - heading:
            lines: []
  phone:
    values:
      value:
        heading: By Phone
        icon: phone
        items:
          - heading:
            phone: