# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profile"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  profiles:
    - person:
      name: Firstname Lastname
      heading: Heading
      quote: Quote.
      thumbnail:
      thumbnail_alt:
      also_see:
        - url:
          text:
          ref:
      show: 2024-09-01
      hide: 2099-09-01
  config:
    name: profile
    edit_mode_only: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  hide:
    type: datetime
    options:
      timezone: America/New_York
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  person:
    type: select
    options:
      allow_empty: true
      values: data.people_data
  show:
    type: datetime
  use_common_wrapper:
    type: auto
    hidden: true