# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Quote"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  quote_text:
  quote_author:
  title:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
      remove_container_background: false
    layout:
      buffer:
      margin:
      max_cols: 12
      padding: py-6 py-xxl-7
    config:
      name:
      instance:
      edit_mode_only: false
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  quote_text:
    type: textarea
  quotemark:
    type: select
    options:
      values: _select_data.brand_colors
      value-key: class