# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Top Story"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Top Story
  tags:
    - top-story
  hide_author: false
  show_content: false
  is_dynamic: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  is_dynamic:
    hidden: true
  tags:
    type: multiselect
    options:
      allow_create: true
      allow_empty: true
      values:
        - featured