# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Tabs"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  tabs:
    - name: Tab 1
      image:
      alt_text:
      label: Label
      heading: Tab Heading
      text: Tab 1 text.
      ctas:
  settings:
    styles:
      audience: general
      tone: default
      color_palette: option-1
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      buffer:
      margin:
      padding: py-6 py-xxl-7
    config:
      name: tabs
      edit_mode_only: false
      include_heading_postscript: false
      show: 2024-09-01
      hide: 2099-09-01
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alt_text:
    hidden: '!image'
    options:
      required: true
  hide:
    type: datetime
    options:
      timezone: America/New_York
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  show:
    type: datetime
  text:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  use_common_wrapper:
    type: auto
    hidden: true