# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Profiles Collection"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  profiles:
    - person:
  config:
    name: profile-collection
    edit_mode_only: false
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  include_heading_postscript:
    hidden: true
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  person:
    type: select
    options:
      allow_empty: true
      values: data.people_data
  use_common_wrapper:
    type: auto
    hidden: true