# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Component Doc"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  overview_markdown:
  when_to_use_markdown:
  in_the_wild:
    - text:
      url:
  content_guidelines:
    - content:
      content_type:
      description:
      max_chars:
      required:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  max_chars:
    type: number
  content_type:
    label: Type
    type: select
    options:
      values:
        - number
        - string
  overview_markdown:
    label: Overview
  required:
    type: checkbox
  when_to_use_markdown:
    label: When to Use