# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Icon Bar"
  description: Horizontal icons with links.
  icon: view_week
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  items:
    - icon: book
      text: Text
      url:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      butter:
      margin:
      padding: py-5
    config:
      edit_mode_only: false
      include_heading_postscript: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: