# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_blocks
    - sidebar_blocks
  label: "Cards - Simple - Vertical"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  items:
    - title: Item 1 Title
      text: Item 1 text.
      url:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: