# Metadata about this component, to be used in the CMS
spec:
  structures:
    - detail_blocks
  label: "Alert"
  description:
  icon: info
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  markdown: Text.
  alert_type: info
  icon:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  alert_type:
    type: select
    options:
      allow_empty: true
      values:
        - _select_data.alert_types
      value_key: type
    cascade: true
  is_dynamic:
    hidden: true
  markdown:
    options:
      allowed_sources:
        - ccdam
_select_data:
  alert_types:
    - name: Danger
      type: danger
    - name: Info
      type: info
    - name: Success
      type: success
    - name: Warning
      type: warning