# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - place_blocks
  label: "Alternating Grid"
  description: Alternating content blocks w/a photo, text call-to-action.
  icon: sync_alt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Alternating Grid Heading
  subheading: Subheading goes here.
  items:
    - heading: Item Heading
      image:
      alt_text:
      copy:
      item_ctas:
  postscript:
    copy:
    postscript_ctas:
  config:
    edit_mode_only: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  copy:
    type: markdown
  item_ctas:
    type: object
    values:
      value: _structures.item_ctas
  postscript_ctas:
    type: object
    values:
      value: _structures.postscript_ctas