# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Alternating Grid"
  description: Alternating content blocks w/a photo, text call-to-action.
  icon: sync_alt
  tags: [Lists]

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Alternating Grid Heading
  subheading: Subheading goes here.
  aria_label:
  items:
    - heading: Item Heading
      image:
      alt_text:
      copy:
      ctas:
  postscript:
    copy:
    # ctas:
  component_settings:
    _bookshop_name: design-system/generic/component-settings
  is_dynamic: false
  is_nested: false
  use_common_wrapper: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  aria_label:
    label: ARIA Label
    hidden: 'heading'
    options:
      required: true
    context:
      content: If your component doesn’t have a heading, it needs an <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label">ARIA label</a> to be accessible. Enter a concise label to provide a clear and useful name for this component e.g. “Featured News Stories.”
  hide:
    type: datetime
    hidden: true
    options:
      timezone: America/New_York
  is_dynamic:
    hidden: true
  is_nested:
    hidden: true
  remove_container_background:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  show:
    hidden: true
    type: datetime
  tint_opacity:
    type: select
    options:
      allow_empty: true
      values: _select_data.tint_opacities
      value_key: value
    comment: >-
      Use to improve text legibility when applying a background image. Disabled
      when blend is enabled.
  alt_text:
    hidden: '!image'
    options:
      required: true
  copy:
    type: markdown
    options:
      allowed_sources:
        - ccdam
  ctas:
    type: array
    options:
      structures: _structures.links
    cascade: true
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
  include_heading_postscript:
    hidden: true
  use_common_wrapper:
    type: auto
    hidden: true
_structures:
  links:
    values:
      - value:
          text:
          icon:
          url: