# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_sidebar_blocks
  label: "Poster"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Headline
  subheading:
  label: 
  image:
  url:
  settings:
    styles:
      audience: general
      tone: default
      card_c: option-2
      bg_subtle: false
      enable_blend: false
      tint_opacity: '0.7'
  is_dynamic: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  card_c:
    type: choice
    options:
      allow_empty: false
      values: _select_data.color_palettes
      value_key: class
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
    cascade: true
  is_dynamic:
    hidden: true
  settings:
    type: object
    options:
      subtype: tabbed
  tint_opacity:
    hidden: true
  tone:
    type: choice
    options:
      allow_empty: false
      values:
        - name: Default
          class: default
        - name: Reserved
          class: reserved
        - name: Loud
          class: loud
        - name: Let’s Go!
          class: lets-go
      value_key: class
_select_data:
  color_palettes:
    - name: Option 1
      class: option-1
    - name: Option 2
      class: option-2
    - name: Option 3
      class: option-3
    - name: Option 4
      class: option-4
    - name: Option 5
      class: option-5
    - name: Option 6
      class: option-6
    - name: Option 7
      class: option-7
    - name: Option 8
      class: option-8