# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks_sm
    - detail_sidebar_blocks
  label: "Poster"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Headline
  subheading:
  label: 
  image:
  url:
  settings:
    styles:
      audience:
      tone:
      card_c: option-2
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  audience:
    type: choice
    options:
      allow_empty: false
      values:
        - name: General
          class: general
        - name: Academic / Traditional
          class: alumni
        - name: Modern + Formal
          class: leaders_partners
        - name: Prospective Students
          class: prospective_students
      value_key: class
    label: Style
  image:
    type: image
    options:
      allowed_sources:
        - ccdam
      width: 1920
      height: 1080
    cascade: true
  settings:
    type: object
    options:
      subtype: tabbed