# Metadata about this component, to be used in the CMS
spec:
  structures:
    - column_blocks
    - column_blocks_sm
  label: "Benefits Checklist"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading.
  items:
    - title: Item 1 Title
      icon:
      label:
      badge:
      text: Item 1 text.
      ctas:
  benefits_icon:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  badge:
    hidden: true
  config:
    hidden: true
  layout:
    hidden: true
  label:
    hidden: true
  text:
    type: markdown
  benefits_icon:
    label: Icon
    type: select
    options:
      values:
        - name: Checkmark
          class: check
        - name: Arrow
          class: arrow-right
      value_key: class