# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Page Collection Vertical - Sticky"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Heading
  subheading: Subheading goes here.
  items:
    - title: Item 1 Title
      text: Item 1 text.
      url:
  postscript:
    copy:
    ctas:
  settings:
    styles:
      audience:
      tone:
      color_palette:
      bg_subtle:
      enable_blend: false
      tint_opacity: '0.7'
    layout:
      butter:
      margin:
      padding: py-6 py-xxl-7
    config:
      edit_mode_only: false
      include_heading_postscript: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: